# Generated by Django 3.2.18 on 2023-04-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20230429_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='updated_on',
        ),
    ]
